# test环境配置
server {
    listen 3000;
    root /usr/share/nginx/html/;
    index index.html index.htm;
    server_name sado-platform-test.stepfun-inc.net;
    proxy_buffering off;
    proxy_cache off;
    proxy_connect_timeout 10s;
    proxy_send_timeout 10s;
    proxy_read_timeout 600s;

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location / {
        
        add_header Content-Security-Policy-Report-Only "default-src 'self' *.basemind.com *.stepfun-inc.com *.stepfun-inc.net *.volces.com at.alicdn.com blob: data:;img-src 'self' * http://* data: blob:;media-src 'self' * http://* data: blob:;style-src 'self' 'unsafe-inline' *.basemind.com *.stepfun-inc.com *.stepfun-inc.net at.alicdn.com cdnjs.cloudflare.com;script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:;connect-src 'self' *.aliyuncs.com http://*.aliyuncs.com *.basemind.com *.stepfun-inc.com *.stepfun-inc.net *.volces.com;font-src 'self' * http://* data: blob:;report-uri https://csp.basemind.com/report";
        
        add_header Access-Control-Allow-Origin *;
        add_header 'Access-Control-Allow-Headers' 'X-Requested-With, access_token, clientType, Content-Type, accessToken, accessSign, X-Request-Uid';
        add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' *;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'X-Requested-With, access_token, clientType, Content-Type, accessToken, accessSign, X-Request-Uid';
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            add_header 'Access-Control-Max-Age' 1728000;
            return 204;
        }
        try_files $uri $uri/ /index.html;
    }
}
